connection:
  retry_timeout: 1.0
udp_connection:
  device_port_dp: 2368
serial_connection:
  serial_device: "/dev/janeth/velodyne"
  baud_rate: 115200
sensor:
  buffer_capacity: 100000
  min_distance: 0.9
  max_distance: 120.0
  device_name: "Velodyne HDL-64E S2"
  spin_rate: 300
diagnostics:
  dp_min_freq: 2777.73
  dp_max_freq: 4166.6
ros:
  queue_depth: 100
  frame_id: "/velodyne_link"
  acquisition_loop_rate: 4166.6
